namespace Kiota.Builder.Writers.PowerShell;

/// <summary>
/// Provides the static C# source code templates for PowerShell infrastructure classes
/// that are written alongside the generated SDK code.
/// </summary>
internal static class PowerShellInfrastructureTemplates
{
    internal const string CmdletBaseClassName = "KiotaPSCmdletBase";
    internal const string JobClassName = "KiotaPSJob";

    /// <summary>Marker used in CodeClass.Documentation to flag a static-template helper class.</summary>
    internal const string StaticTemplateMarker = "KiotaStaticHelper";

    internal static string GetCmdletBaseTemplate(string namespaceName) => $@"// <auto-generated/>
#pragma warning disable CS1591
using System;
using System.Management.Automation;
using System.Threading;
using System.Threading.Tasks;

namespace {namespaceName};

/// <summary>Abstract base class for all Kiota-generated PowerShell cmdlets.</summary>
[global::System.CodeDom.Compiler.GeneratedCode(""Kiota"", ""{Kiota.Generated.KiotaVersion.CurrentMajor()}"")]
public abstract class {CmdletBaseClassName} : PSCmdlet
{{
    /// <summary>Returns the result as a background job instead of blocking.</summary>
    [Parameter]
    public SwitchParameter AsJob {{ get; set; }}

    /// <inheritdoc />
    protected override void ProcessRecord()
    {{
        if (AsJob.IsPresent)
        {{
            var job = new {JobClassName}(ExecuteAsync(CancellationToken.None), MyInvocation.MyCommand.Name);
            JobRepository.Add(job);
            WriteObject(job);
        }}
        else
        {{
            var result = ExecuteAsync(CancellationToken.None).GetAwaiter().GetResult();
            if (result is not null)
                WriteObject(result, true);
        }}
    }}

    /// <summary>Executes the underlying API operation asynchronously.</summary>
    protected abstract Task<object?> ExecuteAsync(CancellationToken cancellationToken);
}}
#pragma warning restore CS1591
";

    internal static string GetJobTemplate(string namespaceName) => $@"// <auto-generated/>
#pragma warning disable CS1591
using System;
using System.Management.Automation;
using System.Threading.Tasks;

namespace {namespaceName};

/// <summary>A PowerShell Job2 that wraps an asynchronous Kiota task.</summary>
[global::System.CodeDom.Compiler.GeneratedCode(""Kiota"", ""{Kiota.Generated.KiotaVersion.CurrentMajor()}"")]
public sealed class {JobClassName} : Job2
{{
    private readonly Task<object?> _task;

    /// <summary>Creates a new <see cref=""{JobClassName}""/> wrapping the given task.</summary>
    public {JobClassName}(Task<object?> task, string commandName) : base(commandName, commandName)
    {{
        _task = task ?? throw new ArgumentNullException(nameof(task));
        SetJobState(JobState.Running);
        _task.ContinueWith(OnTaskCompleted, TaskScheduler.Default);
    }}

    private void OnTaskCompleted(Task<object?> task)
    {{
        if (task.IsFaulted)
        {{
            var error = new ErrorRecord(
                task.Exception?.InnerException ?? task.Exception ?? new InvalidOperationException(),
                ""TaskFailed"", ErrorCategory.NotSpecified, null);
            Error.Add(error);
            SetJobState(JobState.Failed);
        }}
        else if (task.IsCanceled)
        {{
            SetJobState(JobState.Stopped);
        }}
        else
        {{
            if (task.Result is not null)
                Output.Add(new PSObject(task.Result));
            SetJobState(JobState.Completed);
        }}
    }}

    /// <inheritdoc />
    public override string StatusMessage => _task.Status.ToString();
    /// <inheritdoc />
    public override bool HasMoreData => Output.Count > 0 || Error.Count > 0;
    /// <inheritdoc />
    public override string Location => ""Local"";

    /// <inheritdoc />
    public override void StopJob() => SetJobState(JobState.Stopped);
    /// <inheritdoc />
    public override void ResumeJob() {{ }}
    /// <inheritdoc />
    public override void SuspendJob() {{ }}
    /// <inheritdoc />
    public override void UnblockJob() {{ }}
}}
#pragma warning restore CS1591
";
}
