using System;
using System.IO;
using System.Linq;
using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;
using Kiota.Builder.Writers.PowerShell;
using Xunit;

namespace Kiota.Builder.Tests.Writers.PowerShell;

/// <summary>
/// Tests for <see cref="PowerShellCodeClassDeclarationWriter"/>.
/// Covers:
///   - Static helper classes (KiotaPSCmdletBase, KiotaPSJob) write full C# template content.
///   - Cmdlet wrapper classes get [Cmdlet] and [OutputType] attributes.
///   - Regular (non-cmdlet) classes fall through to the CSharp base writer behaviour.
/// </summary>
public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly PowerShellCodeClassDeclarationWriter classWriter;
    private readonly PowerShellConventionService conventions;

    public CodeClassDeclarationWriterTests()
    {
        conventions = new PowerShellConventionService();
        classWriter = new PowerShellCodeClassDeclarationWriter(conventions);
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.PowerShell, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    // -----------------------------------------------------------------------
    // Static helper: KiotaPSCmdletBase
    // -----------------------------------------------------------------------

    [Fact]
    public void WritesCmdletBaseTemplateForKiotaPSCmdletBaseClass()
    {
        var ns = SetupNamespace("MyClient.Cmdlets");
        var helperClass = CreateStaticHelperClass(ns, PowerShellInfrastructureTemplates.CmdletBaseClassName);

        classWriter.WriteCodeElement(helperClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("abstract class KiotaPSCmdletBase", result);
        Assert.Contains("PSCmdlet", result);
        Assert.Contains("AsJob", result);
        Assert.Contains("ProcessRecord", result);
        Assert.Contains("ExecuteAsync", result);
        Assert.Contains("// <auto-generated/>", result);
    }

    [Fact]
    public void WritesCmdletBaseNamespaceInTemplate()
    {
        var ns = SetupNamespace("My.Module.Cmdlets");
        var helperClass = CreateStaticHelperClass(ns, PowerShellInfrastructureTemplates.CmdletBaseClassName);

        classWriter.WriteCodeElement(helperClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("namespace My.Module.Cmdlets", result);
    }

    // -----------------------------------------------------------------------
    // Static helper: KiotaPSJob
    // -----------------------------------------------------------------------

    [Fact]
    public void WritesJobTemplateForKiotaPSJobClass()
    {
        var ns = SetupNamespace("MyClient.Cmdlets");
        var jobClass = CreateStaticHelperClass(ns, PowerShellInfrastructureTemplates.JobClassName);

        classWriter.WriteCodeElement(jobClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("sealed class KiotaPSJob", result);
        Assert.Contains("Job2", result);
        Assert.Contains("StopJob", result);
        Assert.Contains("ResumeJob", result);
        Assert.Contains("SuspendJob", result);
        Assert.Contains("UnblockJob", result);
        Assert.Contains("// <auto-generated/>", result);
    }

    [Fact]
    public void WritesJobNamespaceInTemplate()
    {
        var ns = SetupNamespace("Another.Cmdlets");
        var jobClass = CreateStaticHelperClass(ns, PowerShellInfrastructureTemplates.JobClassName);

        classWriter.WriteCodeElement(jobClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("namespace Another.Cmdlets", result);
    }

    // -----------------------------------------------------------------------
    // Cmdlet wrapper class declaration
    // -----------------------------------------------------------------------

    [Fact]
    public void WritesCmdletAttributeForCmdletClass()
    {
        var (ns, cmdletClass) = SetupCmdletClass("GetUserCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("[Cmdlet(", result);
        Assert.Contains("VerbsCommon.Get", result);
        Assert.Contains("\"User\"", result);
    }

    [Fact]
    public void WritesGeneratedCodeAttributeForCmdletClass()
    {
        var (ns, cmdletClass) = SetupCmdletClass("NewMessageCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(", result);
    }

    [Fact]
    public void WritesAutoGeneratedHeaderForCmdletClass()
    {
        var (ns, cmdletClass) = SetupCmdletClass("GetItemCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("// <auto-generated/>", result);
    }

    [Fact]
    public void WritesNamespaceForCmdletClass()
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("MyClient.Cmdlets");
        var cmdletClass = ns.AddClass(new CodeClass
        {
            Name = "GetUserCmdlet",
            Kind = CodeClassKind.Custom,
        }).First();

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("namespace MyClient.Cmdlets", result);
    }

    [Fact]
    public void WritesCmdletAttributeVerbMapping_NewVerb()
    {
        var (ns, cmdletClass) = SetupCmdletClass("NewDocumentCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("VerbsCommon.New", result);
        Assert.Contains("\"Document\"", result);
    }

    [Fact]
    public void WritesCmdletAttributeVerbMapping_RemoveVerb()
    {
        var (ns, cmdletClass) = SetupCmdletClass("RemoveFileCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("VerbsCommon.Remove", result);
        Assert.Contains("\"File\"", result);
    }

    [Fact]
    public void WritesCmdletAttributeVerbMapping_SetVerb()
    {
        var (ns, cmdletClass) = SetupCmdletClass("SetConfigCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("VerbsCommon.Set", result);
        Assert.Contains("\"Config\"", result);
    }

    [Fact]
    public void WritesCmdletAttributeVerbMapping_UpdateVerb()
    {
        var (ns, cmdletClass) = SetupCmdletClass("UpdateRecordCmdlet");

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("VerbsData.Update", result);
        Assert.Contains("\"Record\"", result);
    }

    [Fact]
    public void WritesInheritanceForCmdletClass()
    {
        var (ns, cmdletClass) = SetupCmdletClass("GetUserCmdlet");
        cmdletClass.StartBlock.Inherits = new CodeType
        {
            Name = "KiotaPSCmdletBase",
            IsExternal = false,
        };

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains(": KiotaPSCmdletBase", result);
    }

    [Fact]
    public void WritesOutputTypeAttributeWhenExecuteAsyncHasTypedReturn()
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("MyClient.Cmdlets");
        var returnModel = root.AddClass(new CodeClass { Name = "UserModel", Kind = CodeClassKind.Model }).First();
        var cmdletClass = ns.AddClass(new CodeClass
        {
            Name = "GetUserCmdlet",
            Kind = CodeClassKind.Custom,
        }).First();
        cmdletClass.AddMethod(new CodeMethod
        {
            Name = "ExecuteAsync",
            Kind = CodeMethodKind.Custom,
            ReturnType = new CodeType { Name = "UserModel", TypeDefinition = returnModel },
        });

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("[OutputType(typeof(UserModel))]", result);
    }

    [Fact]
    public void DoesNotWriteOutputTypeForObjectReturnType()
    {
        var (_, cmdletClass) = SetupCmdletClass("GetAnyCmdlet");
        cmdletClass.AddMethod(new CodeMethod
        {
            Name = "ExecuteAsync",
            Kind = CodeMethodKind.Custom,
            ReturnType = new CodeType { Name = "object", IsNullable = true },
        });

        classWriter.WriteCodeElement(cmdletClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.DoesNotContain("[OutputType(", result);
    }

    // -----------------------------------------------------------------------
    // Regular (non-cmdlet) class — falls through to CSharp base
    // -----------------------------------------------------------------------

    [Fact]
    public void WritesRegularCSharpClassForNonCmdletClass()
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("MyClient");
        var regularClass = ns.AddClass(new CodeClass
        {
            Name = "SomeModel",
            Kind = CodeClassKind.Model,
        }).First();

        classWriter.WriteCodeElement(regularClass.StartBlock, writer);
        var result = tw.ToString();

        Assert.Contains("public partial class SomeModel", result);
        Assert.Contains("// <auto-generated/>", result);
        Assert.DoesNotContain("[Cmdlet(", result);
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static CodeNamespace SetupNamespace(string nsName)
    {
        var root = CodeNamespace.InitRootNamespace();
        return root.AddNamespace(nsName);
    }

    private static CodeClass CreateStaticHelperClass(CodeNamespace ns, string className)
    {
        return ns.AddClass(new CodeClass
        {
            Name = className,
            Kind = CodeClassKind.Custom,
            Documentation = new CodeDocumentation
            {
                DescriptionTemplate = PowerShellInfrastructureTemplates.StaticTemplateMarker,
            },
        }).First();
    }

    private static (CodeNamespace ns, CodeClass cmdletClass) SetupCmdletClass(string className)
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("TestNs");
        var c = ns.AddClass(new CodeClass
        {
            Name = className,
            Kind = CodeClassKind.Custom,
        }).First();
        return (ns, c);
    }
}
